#!/bin/bash


#####################
# Script to run the navigation terminals as specified on 11/18/2023
# Generated by GPT4 and not tested, use with caution!
####################



# Function to run commands in a new terminal
run_in_new_terminal() {
    gnome-terminal -- bash -c "$1; exec bash"
}

# Start Realsense on Fetch
run_in_new_terminal "ssh fetch@fetch59.local
source ~/ros2_foxy/install/setup.bash
cd ~/ros2_ws
colcon build
. install/setup.bash
ros2 launch realsense2_camera rs_launch.py"

# Verify Realsense
run_in_new_terminal "ssh fetch@fetch59.local
source ~/ros2_foxy/install/setup.bash
rostopic hz /ros2_camera/color/image_raw"

# Run Image Compression Node on Fetch
run_in_new_terminal "ssh fetch@fetch59.local
source ~/ros2_foxy/install/setup.bash
cd ~/ros2_ws
colcon build
. install/setup.bash
ros2 run image_compression color_image_compression_node.py"

# Verify Image Compression
run_in_new_terminal "ssh fetch@fetch59.local
source ~/ros2_foxy/install/setup.bash
rostopic hz /image_compressed"

# Run ROS2 to ROS1 Bridge
run_in_new_terminal "ssh fetch@fetch59.local
source /opt/ros/noetic/setup.bash
rosparam load ~/ros2_ws/src/image_compression/params/bridge.yaml
source ~/ros2_foxy/install/setup.bash
ros2 run ros1_bridge parameter_bridge"

# Run Talker Node in ROS2 on Computer
run_in_new_terminal "ros2 run demo_nodes_cpp talker"

# Run Listener in ROS1 on Fetch
run_in_new_terminal "ssh fetch@fetch59.local
source /opt/ros/noetic/setup.bash
rosrun roscpp_tutorials listener"

# Run Image Uncompression Node on Computer
run_in_new_terminal "cd ~/lifelong_lerf_ws
colcon build
. install/setup.bash
ros2 run camera_bringup realsense_compressed_converter.py"

# Verify Image Uncompression
run_in_new_terminal "rostopic hz /repub_image_raw"

# Run RTABMAP and RVIZ on Computer
run_in_new_terminal "cd ~/lifelong_lerf_ws
colcon build
. install/setup.bash
ros2 launch realsense_rtabmap_slam_bringup new_rtabmap.launch.py"

# Run Navigation on Computer
run_in_new_terminal "cd ~/lifelong_lerf_ws
colcon build
. install/setup.bash
ros2 launch realsense_rtabmap_slam_bringup navigation.launch.py"

# Verify Navigation
run_in_new_terminal "rostopic echo /cmd_vel
rostopic echo /navigate_to_pose/_action/status"

# Run Twist to String Conversion on Computer
run_in_new_terminal "cd ~/lifelong_lerf_ws
colcon build
. install/setup.bash
ros2 run realsense_rtabmap_slam_bringup twist_to_string.py"

# Run String to Twist Conversion on Fetch
run_in_new_terminal "ssh fetch@fetch59.local
source /opt/ros/noetic/setup.bash
cd lifelong_lerf_fetch_ws
catkin_make
source devel/setup.bash
rosrun nuc_bridge string_to_twist.py"

echo "All commands executed. Check each terminal for output."
